### ISSUE TITLE
need pyfeast to run tests

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik-feature-selection#3]
The library [`pyfeast`](https://github.com/mutantturkey/PyFeast)  is not available via conda, and seems not to be python3 ready.
The library is used in the tests, which result in error as a result.

We should either:

1) port `pyfeast` to python3 and add a conda recipe, or
2) change the tests not to be dependent on `pyfeast`

**Comment by stuarteberg** [comment]
>The library pyfeast is not available via conda

Looks like I got it working a long time ago, and published a package on the old `ilastik` channel:

https://anaconda.org/ilastik/pyfeast/files

>seems not to be python3 ready.

Apparently I have a fork of pyfeast that adds support for Python 3.  (Looks like it was not difficult.)

https://github.com/stuarteberg/PyFeast/commits/master

I must have forgotten to migrate the package to the `ilastik-forge` channel last year.  It also appears I dropped the recipe from `ilastik-build-conda`, but you can still find it in the `python-2` branch:

https://github.com/ilastik/ilastik-build-conda/tree/python-2/pyfeast

(It will need to be updated for Python 3.6, but that might be the only necessary change.

**Comment by wasim-hossain** [comment]
pyfeast is dependent on Python 2.7, is there any version available for python 3.X?
